(function(g,r,d,f,l,m){"use strict";const{FormSection:b,FormRow:n,FormText:u}=m.Forms;function w(){return l.React.createElement(b,{title:"\u{1F3B5} Rickroll Plugin Settings"},l.React.createElement(n,{label:"How to use",trailing:n.Arrow},l.React.createElement(u,null,'Type "/rick" or "/rickroll" in any channel! Your message becomes rickroll text and YOU hear the sound locally.')),l.React.createElement(n,{label:"Features",trailing:n.Arrow},l.React.createElement(u,null,`\u2022 Plays audio locally (only you hear it)
\u2022 Replaces your message with rickroll text
\u2022 Works in any Discord channel
\u2022 Multiple backup audio sources
\u2022 Fallback beep sound if audio fails`)),l.React.createElement(n,{label:"Pro Tips",trailing:n.Arrow},l.React.createElement(u,null,`\u2022 Use "/rick" for a quick rickroll
\u2022 Perfect for pranking friends
\u2022 The element of surprise is key!
\u2022 Great for lightening the mood
\u2022 Rick Astley would be proud \u{1F57A}`)),l.React.createElement(n,{label:"Warning",trailing:n.Arrow},l.React.createElement(u,{style:{color:"#ff6b6b"}},"Use responsibly! Don't spam rickrolls or your friends might get annoyed. Remember: with great power comes great ricksponsibility! \u{1F3B5}")))}let c;const p=["https://files.catbox.moe/pbtj68.mp3","https://audio.jukehost.co.uk/tFkLhbRaHjQGx7UHwsQMEe3eTfQNK5H4","https://www.soundjay.com/misc/sounds/bell-ringing-05.wav"],y=function(){try{const e=new Audio;let o=0;const i=function(){if(o>=p.length){r.logger.log("All rickroll URLs failed, playing local beep");const t=new(window.AudioContext||window.webkitAudioContext),a=t.createOscillator(),s=t.createGain();a.connect(s),s.connect(t.destination),a.frequency.value=800,a.type="sine",s.gain.setValueAtTime(.3,t.currentTime),s.gain.exponentialRampToValueAtTime(.01,t.currentTime+1),a.start(t.currentTime),a.stop(t.currentTime+1);return}e.src=p[o],e.volume=.7,e.play().catch(function(){o++,i()})};e.addEventListener("error",function(){o++,i()}),i(),r.logger.log("\u{1F3B5} Never gonna give you up! \u{1F3B5}")}catch(e){r.logger.log("Failed to rickroll:",e)}},k=function(e){const o=e.content?.toLowerCase()||"";return o.includes("/rick")||o.includes("/rickroll")};var h={onLoad:function(){r.logger.log("\u{1F3B5} Rickroll Plugin Loaded! Type /rick to rickroll! \u{1F3B5}");try{const e=d.findByStoreName("MessageActions");if(e&&e.sendMessage)c=f.before("sendMessage",e,function(o){const[i,t]=o;k(t)&&(setTimeout(function(){y()},100),t.content=`\u{1F3B5} **RICKROLLED!** \u{1F3B5}
*Never gonna give you up, never gonna let you down!* \u{1F57A}\u{1F483}

*(You just got rickrolled by yourself!)*`,r.logger.log("Rickroll activated! \u{1F3B5}"))}),r.logger.log("Successfully patched MessageActions for rickroll detection!");else{r.logger.log("Could not find MessageActions - trying alternative approach...");const o=d.findByStoreName("MessageStore");o&&(c=f.before("dispatch",o,function(i){const[t]=i;t.type==="MESSAGE_CREATE"&&t.message&&k(t.message)&&setTimeout(function(){y()},100)}))}}catch(e){r.logger.log("Error setting up rickroll plugin:",e)}},onUnload:function(){r.logger.log("\u{1F3B5} Rickroll Plugin Unloaded - No more rickrolls! \u{1F3B5}"),c&&(c(),c=null)},settings:w};return g.default=h,Object.defineProperty(g,"__esModule",{value:!0}),g})({},vendetta,vendetta.metro,vendetta.patcher,vendetta.metro.common,vendetta.ui.components);
